dependencies:
  - docker
  - docker-compose

executionClients:
  - nethermind

consensusClients:
  - lighthouse
  - lodestar
  - prysm
  - teku
 
validatorClients:
  - lighthouse
  - lodestar
  - prysm
  - teku

logs:
  logLevel: debug